#!/bin/bash
# Absolute-path shebang not `/usr/bin/env bash`: the fail-open guarantee must hold
# even under a stripped PATH where `env bash` exits 127.
# comment-discipline guard. On an Edit/Write/MultiEdit it inspects only the *added* text
# and reports the high-confidence noise patterns. Silence is the common case.
#
# ONE DETECTOR, TWO LANES — the event decides which:
#
#   PostToolUse (default when no event name is present) — WARN. Emits
#   {"hookSpecificOutput":{"hookEventName":"PostToolUse","additionalContext":...}}, exit 0
#   — the one non-blocking channel the executing model actually receives; plain stdout
#   text with exit 0 never reaches it (same reasoning as task-runner/hooks/scope.sh).
#   `additionalContext` is NOT a blocking key: it adds context, it cannot veto. This lane
#   never blocks anything, ever.
#
#   PreToolUse — DENY, narrowly. Warning after the write is warning about a file that is
#   already on disk, and a warning the model may read and walk past is not enforcement.
#   So the two strictest categories — a comment restating the next line, and commented-out
#   code — are denied BEFORE the write, and only those. Banners, bare TODOs, dead
#   docblock tags and change-narration comments stay warn-only: they are house-style
#   calls, a TODO can be a legitimate mid-task marker, and narration cues are phrase
#   matches that can catch a legitimate why-comment phrased as a change event.
#
# BOUNDED: the deny is ONE-SHOT PER FILE PER SESSION. A second edit to the same file goes
# through and the PostToolUse lane warns instead, so a false positive costs one extra turn
# and can never wedge a session. Without a session_id the bound cannot be enforced, so the
# deny is withheld entirely. Generated files (a `@generated` / `generated by` / `do not
# edit` marker in the first five added lines) are exempt, as are the paths and extensions
# already excluded below.
#
# Fail-open throughout: a missing jq/awk, or any error, exits 0 and denies nothing.
{
  command -v jq  >/dev/null 2>&1 || exit 0
  command -v awk >/dev/null 2>&1 || exit 0

  input=$(cat)
  # One detector, two lanes. Absent event name = PostToolUse, the original behavior.
  event=$(printf '%s' "$input" | jq -r '.hook_event_name // "PostToolUse"' 2>/dev/null) || exit 0
  cwd=$(printf '%s' "$input" | jq -r '.cwd // empty' 2>/dev/null)
  tool=$(printf '%s' "$input" | jq -r '.tool_name // empty' 2>/dev/null) || exit 0
  case "$tool" in Edit|Write|MultiEdit) ;; *) exit 0 ;; esac

  fp=$(printf '%s' "$input" | jq -r '.tool_input.file_path // empty' 2>/dev/null) || exit 0
  [ -n "$fp" ] || exit 0

  # Generated, vendored, and tooling paths are exempt: their header banners and usage
  # blocks are deliberate, and nobody edits them by hand for readability.
  #
  # Tested against the LOGICAL path — a worktree prefix stripped — because this
  # marketplace places worktrees at `.claude/worktrees/<branch>`, and `*/.claude/*`
  # was therefore exempting every source file written by a track run. See
  # hooks/paths.sh. A missing lib leaves lp = fp, i.e. the old behaviour.
  lp="$fp"
  . "$(dirname "$0")/paths.sh" 2>/dev/null
  command -v cd_logical_path >/dev/null 2>&1 && lp=$(cd_logical_path "$fp")
  case "$lp" in
    */.claude/*|*/node_modules/*|*/vendor/*|*/dist/*|*/build/*|*/.git/*) exit 0 ;;
    */scripts/*.sh|*/templates/*|*/plugins/*/hooks/*|*/migrations/*) exit 0 ;;
  esac

  # Code only. Config and prose formats use comments for navigation, which this rule
  # does not govern — so YAML stays OUT deliberately, including docker-compose.yml,
  # CI workflows and k8s manifests, where a `# the web service` header is a real
  # navigation aid rather than a restatement.
  #
  # BUILD FILES ARE CODE, and that is why they are in. A Dockerfile and a Makefile are
  # imperative step lists, not documents: `# install dependencies` above
  # `RUN apt-get install -y …` restates its next line exactly the way `// increment the
  # counter` does above `counter++`, and *.sh has always been governed for that reason.
  # Extensionless names are matched by basename, so the worktree-stripped path is not
  # enough on its own — see the `base` case below.
  case "$fp" in
    *.js|*.jsx|*.ts|*.tsx|*.mjs|*.cjs|*.vue|*.svelte) ;;
    *.php|*.py|*.rb|*.go|*.rs|*.java|*.kt|*.kts|*.swift|*.scala|*.dart) ;;
    *.c|*.h|*.cpp|*.hpp|*.cc|*.cs|*.m|*.mm) ;;
    *.sh|*.bash|*.zsh|*.pl|*.lua|*.ex|*.exs|*.jl|*.r|*.groovy) ;;
    *.sql|*.css|*.scss|*.less|*.graphql|*.tf) ;;
    *.dockerfile|*.mk) ;;
    *)
      case "$(basename "$fp")" in
        Dockerfile|Dockerfile.*|Containerfile|Containerfile.*|Makefile|GNUmakefile) ;;
        *) exit 0 ;;
      esac ;;
  esac

  added=$(printf '%s' "$input" | jq -r '
    [ .tool_input.content    // empty,
      .tool_input.new_string // empty,
      ( .tool_input.edits // [] | map(.new_string // empty) | join("\n") )
    ] | join("\n")' 2>/dev/null) || exit 0
  [ -n "$added" ] || exit 0

  raw=$(printf '%s\n' "$added" | awk '
  function add_tok(set, w,   x) {
    if (w == "") return
    x = tolower(w)
    if (length(x) < 2) return
    set[x] = 1
    if (length(x) > 3 && substr(x, length(x)) == "s") set[substr(x, 1, length(x) - 1)] = 1
  }
  # camelCase and snake_case carry the same words a comment would spell out, so a name
  # only counts as "already says it" once it is split back into those words.
  function split_ident(w, set,   i, c, cur) {
    cur = ""
    for (i = 1; i <= length(w); i++) {
      c = substr(w, i, 1)
      if (c == "_" || c == "$" || c == "-") { add_tok(set, cur); cur = ""; continue }
      if (c ~ /[A-Z]/ && cur != "" && substr(cur, length(cur)) ~ /[a-z0-9]/) {
        add_tok(set, cur); cur = c; continue
      }
      cur = cur c
    }
    add_tok(set, cur)
  }
  function code_tokens(l, set,   n, arr, i, w) {
    n = split(l, arr, /[^A-Za-z0-9_$]+/)
    for (i = 1; i <= n; i++) {
      w = arr[i]
      if (w == "") continue
      add_tok(set, w)
      split_ident(w, set)
    }
  }
  # Operators say in symbols what a restating comment says in words; without this map
  # "// increment the counter" over "counter++" reads as new information.
  function op_tokens(l, set) {
    if (l ~ /\+\+/)   { add_tok(set, "increment"); add_tok(set, "increase"); add_tok(set, "bump"); add_tok(set, "count") }
    if (l ~ /--/)     { add_tok(set, "decrement"); add_tok(set, "decrease"); add_tok(set, "subtract") }
    if (l ~ /\+=/)    { add_tok(set, "add"); add_tok(set, "increment"); add_tok(set, "append"); add_tok(set, "increase") }
    if (l ~ /-=/)     { add_tok(set, "subtract"); add_tok(set, "decrease") }
    if (l ~ /=/)      { add_tok(set, "set"); add_tok(set, "assign"); add_tok(set, "store"); add_tok(set, "save"); add_tok(set, "update"); add_tok(set, "initialize"); add_tok(set, "init"); add_tok(set, "define"); add_tok(set, "declare"); add_tok(set, "value") }
    if (l ~ /(^|[^A-Za-z])return([^A-Za-z]|$)/) { add_tok(set, "return"); add_tok(set, "result"); add_tok(set, "output"); add_tok(set, "give") }
    if (l ~ /(^|[^A-Za-z])if([^A-Za-z]|$)/)     { add_tok(set, "check"); add_tok(set, "handle"); add_tok(set, "test") }
    if (l ~ /(^|[^A-Za-z])(for|while|forEach|foreach|map)([^A-Za-z]|$)/) { add_tok(set, "loop"); add_tok(set, "iterate"); add_tok(set, "over"); add_tok(set, "through"); add_tok(set, "every") }
    if (l ~ /(^|[^A-Za-z])new([^A-Za-z]|$)/)    { add_tok(set, "create"); add_tok(set, "make"); add_tok(set, "instantiate"); add_tok(set, "build"); add_tok(set, "construct") }
    if (l ~ /(^|[^A-Za-z])(throw|raise)([^A-Za-z]|$)/) { add_tok(set, "throw"); add_tok(set, "raise"); add_tok(set, "error"); add_tok(set, "fail") }
    if (l ~ /(^|[^A-Za-z])(delete|remove|unset|splice|drop)([^A-Za-z]|$)/) { add_tok(set, "delete"); add_tok(set, "remove"); add_tok(set, "drop"); add_tok(set, "clear") }
    if (l ~ /(^|[^A-Za-z])(push|append|insert|add)([^A-Za-z]|$)/) { add_tok(set, "add"); add_tok(set, "append"); add_tok(set, "insert") }
    if (l ~ /(^|[^A-Za-z])(import|require|include|use)([^A-Za-z]|$)/) { add_tok(set, "import"); add_tok(set, "load"); add_tok(set, "require"); add_tok(set, "include") }
    if (l ~ /(^|[^A-Za-z])(log|print|echo|puts|printf|println)([^A-Za-z]|$)/) { add_tok(set, "log"); add_tok(set, "print"); add_tok(set, "output"); add_tok(set, "debug"); add_tok(set, "write"); add_tok(set, "show") }
    if (l ~ /(^|[^A-Za-z])(await|async)([^A-Za-z]|$)/) { add_tok(set, "wait"); add_tok(set, "await"); add_tok(set, "async") }
    if (l ~ /(^|[^A-Za-z])(try|catch|except|rescue)([^A-Za-z]|$)/) { add_tok(set, "try"); add_tok(set, "catch"); add_tok(set, "handle"); add_tok(set, "error"); add_tok(set, "guard") }
    if (l ~ /(^|[^A-Za-z])(null|nil|None|undefined)([^A-Za-z]|$)/) { add_tok(set, "clear"); add_tok(set, "reset"); add_tok(set, "empty"); add_tok(set, "blank") }
    if (l ~ /(^|[^A-Za-z])true([^A-Za-z]|$)/)  { add_tok(set, "enable"); add_tok(set, "allow"); add_tok(set, "on") }
    if (l ~ /(^|[^A-Za-z])false([^A-Za-z]|$)/) { add_tok(set, "disable"); add_tok(set, "block"); add_tok(set, "off") }
    if (l ~ /(length|count|size)/)  { add_tok(set, "count"); add_tok(set, "length"); add_tok(set, "size"); add_tok(set, "number"); add_tok(set, "total") }
    if (l ~ /sort/)   { add_tok(set, "sort"); add_tok(set, "order"); add_tok(set, "rank") }
    if (l ~ /filter/) { add_tok(set, "filter"); add_tok(set, "keep"); add_tok(set, "select"); add_tok(set, "exclude") }
    if (l ~ /(function|=>|def )/) { add_tok(set, "define"); add_tok(set, "declare"); add_tok(set, "function"); add_tok(set, "helper") }
    if (l ~ /\+/) { add_tok(set, "add"); add_tok(set, "sum"); add_tok(set, "plus"); add_tok(set, "concat"); add_tok(set, "join"); add_tok(set, "combine") }
    if (l ~ /\*/) { add_tok(set, "multiply"); add_tok(set, "times"); add_tok(set, "product") }
    if (l ~ /\//) { add_tok(set, "divide"); add_tok(set, "ratio") }
    if (l ~ /%/)  { add_tok(set, "modulo"); add_tok(set, "remainder") }
    if (l ~ /[<>]/) { add_tok(set, "compare"); add_tok(set, "greater"); add_tok(set, "less"); add_tok(set, "than"); add_tok(set, "exceeds") }
    if (l ~ /(\?\?|\|\|)/) { add_tok(set, "default"); add_tok(set, "fallback") }
  }
  function cbody(l,   s) {
    s = l
    sub(/^[ \t]+/, "", s)
    if (s ~ /^#!/) return ""
    if (s ~ /^\/\//)  { sub(/^\/\/+[ \t]*/, "", s); return s }
    if (s ~ /^\/\*/)  { sub(/^\/\*+[ \t]*/, "", s); sub(/[ \t]*\*\/[ \t]*$/, "", s); return s }
    if (s ~ /^\*/ && s !~ /^\*[A-Za-z0-9_(]/) { sub(/^\*+[ \t]*/, "", s); sub(/[ \t]*\*\/[ \t]*$/, "", s); return s }
    if (s ~ /^#[ \t]/ || s ~ /^##/) { sub(/^#+[ \t]*/, "", s); return s }
    if (s ~ /^-- /)   { sub(/^--[ \t]*/, "", s); return s }
    return ""
  }
  # Legally required, machine-read, or tool-directive comments are not prose anyone
  # chose to write, so they are outside this rule entirely.
  function exempt(b,   x) {
    x = tolower(b)
    if (x ~ /spdx|copyright|all rights reserved|licensed under|license:|licence:/) return 1
    if (x ~ /eslint-|tslint|jshint|ts-expect-error|ts-ignore|@ts-|type: *ignore|noqa|phpcs:|phpstan-|psalm-|prettier-ignore|biome-ignore|stylelint-|pylint:|rubocop:|nolint|golangci|istanbul ignore|c8 ignore|codecoverageignore|shellcheck|coverage:/) return 1
    return 0
  }
  function is_banner(b,   c) {
    if (b !~ /^[=*#_~-][=*#_~-][=*#_~-]/ && b !~ /[=*#_~-][=*#_~-][=*#_~-][ \t]*$/) return 0
    c = b
    gsub(/[^A-Za-z0-9]/, "", c)
    return (length(c) <= 24)
  }
  function is_code(b) {
    if (b ~ /^[})\];]+[ \t]*;?[ \t]*$/) return 1
    if (b ~ /;[ \t]*$/ && b ~ /[=(]/) return 1
    if (b ~ /^(if|for|while|switch|foreach)[ \t]*\(/) return 1
    if (b ~ /^(return|const|let|var|def|class|function|import|export|public|private|protected|echo|print|new|await|async)[ \t]/ && b ~ /[=({:]/) return 1
    if (b ~ /^[A-Za-z_$][A-Za-z0-9_$.]*\(.*\)[ \t]*;?[ \t]*$/) return 1
    if (b ~ /^[$@]?[A-Za-z_][A-Za-z0-9_]*[ \t]*=[^=]/) return 1
    return 0
  }
  # The diff addressing its reviewer: a comment describing the EDIT — its author, its
  # correctness, the review that asked for it — rather than the code. A why-comment
  # states a standing constraint; a change event ("now handles", "updated to", "fix
  # per review") is stale the moment the change merges. Phrase cues, so warn-only.
  # A ticket, issue, or URL rescues the comment outright: a reference to track is the
  # keep-case form ("Retry cap of 5 as discussed in ADR-12"), same idiom as is_bare_todo.
  function is_narration(b,   x) {
    if (b ~ /#[0-9]/ || b ~ /[A-Z][A-Z0-9]+-[0-9]/ || b ~ /https?:\/\//) return 0
    x = tolower(b)
    if (x ~ /^now that /) return 0
    if (x ~ /^(now|it now|this now|we now) /) return 1
    if (x ~ /(^| )now (correctly|properly) /) return 1
    if (x ~ /^(this|the) (fix|change|update|patch|refactor) (is|was|also|now|makes|ensures|addresses|fixes|resolves|prevents|handles|corrects|improves|adds|removes) /) return 1
    if (x ~ /^fix(ed)?(:| for )/) return 1
    if (x ~ /^(added|removed|renamed|moved|corrected|bugfix|hotfix)[ :]/) return 1
    if (x ~ /^fixes /) return 1
    if (x ~ /^no longer /) return 1
    if (x ~ /as requested|per (the )?review|review feedback|as discussed|addresses (the )?(review|comment|feedback)/) return 1
    if (x ~ /^(updated|changed|switched|migrated|converted|refactored|rewrote|reworked) (to|from|this|the) /) return 1
    if (x ~ /^previously,/) return 1
    if (x ~ /used to (be|return|use)/) return 1
    return 0
  }
  function is_bare_todo(b) {
    if (b !~ /TODO|FIXME|XXX|HACK/) return 0
    if (b ~ /#[0-9]/) return 0
    if (b ~ /[A-Z][A-Z0-9]+-[0-9]/) return 0
    if (b ~ /https?:\/\//) return 0
    return 1
  }
  function is_dead_tag(b,   t, n, arr, i, name, desc, seen, d) {
    if (b ~ /^@returns?[ \t]+void[ \t.]*$/) return 1
    if (b ~ /^@returns?[ \t]*$/) return 1
    if (b ~ /^:param[ \t]/) { t = b; sub(/^:param[ \t]+/, "", t); sub(/:/, " ", t) }
    else if (b ~ /^@param[ \t]/) { t = b; sub(/^@param[ \t]+/, "", t) }
    else return 0
    n = split(t, arr, /[ \t]+/)
    name = ""
    for (i = 1; i <= n && i <= 2; i++) if (arr[i] ~ /^\$/) { name = substr(arr[i], 2); break }
    if (name == "" && n >= 2 && arr[1] ~ /^[A-Za-z_|\\{<]/ && arr[2] ~ /^[A-Za-z_]/) name = arr[2]
    if (name == "" && n == 1) name = arr[1]
    if (name == "") return 0
    seen = 0; desc = ""
    for (i = 1; i <= n; i++) {
      if (!seen && (arr[i] == name || arr[i] == ("$" name))) { seen = 1; continue }
      if (seen) desc = desc " " arr[i]
    }
    if (!seen) return 0
    d = tolower(desc)
    gsub(/[.,:]/, "", d)
    gsub(/^[ \t]+|[ \t]+$/, "", d)
    sub(/^(the|a|an)[ \t]+/, "", d)
    if (d == "") return 1
    gsub(/[ \t]/, "", d)
    return (d == tolower(name))
  }
  # Every content word of the comment must already be recoverable from the code line.
  # Requiring ALL of them, not a ratio, is what keeps this warning credible.
  function restates(b, code,   set, n, arr, i, w, ct, sing) {
    split("", set)
    code_tokens(code, set)
    op_tokens(code, set)
    n = split(b, arr, /[^A-Za-z0-9_]+/)
    ct = 0
    for (i = 1; i <= n; i++) {
      w = tolower(arr[i])
      if (w == "" || length(w) < 2) continue
      if (w in SW) continue
      ct++
      if (w in set) continue
      sing = (length(w) > 3 && substr(w, length(w)) == "s") ? substr(w, 1, length(w) - 1) : ""
      if (sing != "" && (sing in set)) continue
      return 0
    }
    return (ct > 0)
  }
  BEGIN {
    split("the a an to to of for and or is are was were be being been this that these those it its we you i they he she then now here there in on on at by with from as into each all any some if so do does did not no our your their and but when while where which who what how new old up down out off over under again very can will would should could may might must has have had", swl, " ")
    for (i in swl) SW[swl[i]] = 1
    split("restating the next line|section banner|commented-out code|bare TODO|docblock tag repeating the signature|change-narration (describes the edit, not the code)", CATS, "|")
  }
  { L[++T] = $0 }
  END {
    for (i = 1; i <= T; i++) {
      b = cbody(L[i])
      if (b == "" || exempt(b)) continue
      if (is_banner(b))       { H[2]++; total++; continue }
      if (is_code(b))         { H[3]++; total++; continue }
      if (is_bare_todo(b))    { H[4]++; total++; continue }
      if (is_dead_tag(b))     { H[5]++; total++; continue }
      if (is_narration(b))    { H[6]++; total++; continue }
      j = i + 1
      while (j <= T && (L[j] ~ /^[ \t]*$/ || cbody(L[j]) != "")) j++
      if (j <= T && restates(b, L[j])) { H[1]++; total++ }
    }
    if (total == 0) exit 0
    # Line 1 is machine-read by the shell: how many findings are in the two
    # BLOCKABLE categories (restatement, commented-out code). Those two are the
    # strictest detectors here — restates() requires EVERY content word of the
    # comment to be recoverable from the code line, and is_code() matches syntax,
    # not prose. Banners, bare TODOs, dead docblock tags and change-narration
    # comments stay warn-only: they are house-style calls, a TODO can be a
    # legitimate mid-task marker, and narration cues are phrase matches.
    printf "%d\n", (1 in H ? H[1] : 0) + (3 in H ? H[3] : 0)
    parts = ""
    for (k = 1; k <= 6; k++) {
      if (!(k in H)) continue
      parts = parts (parts == "" ? "" : ", ") H[k] " " CATS[k]
    }
    printf "comment-discipline: %d added %s (%s) — check the routing table in the comment-discipline skill for where those facts belong.\n", total, (total == 1 ? "comment looks like noise" : "comments look like noise"), parts
  }')
  [ -n "$raw" ] || exit 0
  blockable=$(printf '%s\n' "$raw" | head -1)
  warn=$(printf '%s\n' "$raw" | tail -n +2)
  [ -n "$warn" ] || exit 0
  case "$blockable" in ''|*[!0-9]*) blockable=0 ;; esac

  # jq builds the envelope so the message stays valid JSON whatever the comment text
  # contains. jq presence is guaranteed by the guard at the top of the block.
  if [ "$event" != "PreToolUse" ]; then
    jq -cn --arg ctx "$warn" \
      '{hookSpecificOutput:{hookEventName:"PostToolUse",additionalContext:$ctx}}'
    exit 0
  fi

  # ---- PreToolUse lane: deny the two blockable categories, ONCE per file ----
  #
  # WHY DENY AND NOT ASK: the model wrote the comment, so the model is the right
  # audience for the correction. `ask` would interrupt the HUMAN for a style nit,
  # once per tripping edit — during a task run that is dozens of prompts about
  # something the human did not write and cannot usefully adjudicate.
  #
  # WHY ONE-SHOT PER FILE: a deny the model cannot satisfy would otherwise loop.
  # The second attempt on the same file in the same session is allowed through,
  # and the PostToolUse lane warns on it instead — so a false positive costs one
  # extra turn, never a wedged session. Same bounding idea as task-runner's
  # one-block-per-commit completion gate.
  #
  # THE BOUND IS THE PRECONDITION, NOT A COURTESY. Every input the one-shot needs —
  # a session id, a cwd, a hashable path, and a marker that actually landed on disk —
  # is checked BEFORE the deny is emitted, and any one of them missing withholds the
  # deny entirely. An earlier revision wrote the marker with `2>/dev/null` and ignored
  # the result, which meant a read-only `$cwd/.claude` (sealed root when cwd was
  # absent, a 555 checkout, a container mount) produced a deny on every attempt with
  # nothing recording that it had fired: precisely the unwedgeable loop this comment
  # promised could not happen. Blocking is only defensible while it is bounded, so a
  # bound that cannot be recorded means no block at all.
  [ "$blockable" -gt 0 ] || exit 0

  # Generated output declares itself in its own header; its banners are deliberate.
  printf '%s\n' "$added" | head -5 | grep -qiE '@generated|generated by|do not edit' && exit 0

  # CONTEXT KEY, not session key. PostToolUse is the only hook channel that reaches
  # subagents at all, and a subagent shares its parent's session_id while getting its
  # own transcript. Keying a one-shot on session_id therefore dedups the worker against
  # nudges only the PARENT ever saw, so the context where most fan-out code is written
  # is the one context this never speaks in. Pattern and rationale: lean/hooks/budget.sh:10.
  sid=$(printf '%s' "$input" | jq -r '.transcript_path // .session_id // empty' 2>/dev/null)
  [ -n "$sid" ] || exit 0                     # cannot bound the one-shot → do not block
  [ -n "$cwd" ] || exit 0                     # no cwd → nowhere to record the bound
  key=$(printf '%s' "$fp" | (command -v shasum >/dev/null 2>&1 && shasum || cksum) 2>/dev/null | cut -d' ' -f1)
  [ -n "$key" ] || exit 0
  # THE KEY IS A PATH, SO IT MUST BE HASHED BEFORE IT CAN BE A FILENAME. `.transcript_path`
  # is an absolute path; interpolating it raw builds `…/blocked-/Users/…/x.jsonl-<key>`,
  # whose parents `mkdir -p "$cwd/.claude/comment-discipline"` never creates. Every write
  # then fails, the withhold below fires, and the deny is silently absent on every edit of
  # every file — the tooth reads as present in this file and is gone in every real session.
  # Hashed with the same cksum idiom as code-review/hooks/conventions.sh:59 and
  # lean/hooks/budget.sh:64, which were the two that got this right.
  ctx=$(printf '%s' "$sid" | cksum 2>/dev/null | cut -d' ' -f1)
  [ -n "$ctx" ] || exit 0
  marker="$cwd/.claude/comment-discipline/blocked-$ctx-$key"
  [ -e "$marker" ] && exit 0
  mkdir -p "$cwd/.claude/comment-discipline" 2>/dev/null || exit 0
  : > "$marker" 2>/dev/null || exit 0
  [ -e "$marker" ] || exit 0                  # marker did not land → deny stays unbounded → withhold

  reason=$(printf '%s Write the edit again without them: a comment restating the next line, or a line of commented-out code, has no fact to carry — delete it or move the fact to a name, a type, or a test. Blocked once per file; a repeat edit to this file goes through with a warning instead.' "$warn")
  jq -cn --arg r "$reason" \
    '{hookSpecificOutput:{hookEventName:"PreToolUse",permissionDecision:"deny",permissionDecisionReason:$r}}'
} 2>/dev/null
exit 0
