# Shared path scoping for comment-discipline's two file guards (scan.sh, density.sh).
# Not executable and has no shebang: it is only ever sourced.
#
# WHY THIS EXISTS. Both guards skip `*/.claude/*` — meant to exempt the Claude
# configuration directory, whose contents nobody edits for readability. The pattern
# also matched every source file inside a git worktree, because this marketplace's own
# skills place worktrees at `.claude/worktrees/<branch>`: `worktree-isolation` says so,
# and `track-orchestration/references/algorithm.md` literally runs
# `git worktree add .claude/worktrees/<run-branch>-track-<slug>`. So the parallel-track
# execution path wrote all of its code into the one directory the comment guard was
# hardcoded to ignore, and a 73-file run drew not a single warning — one of two
# independent reasons that guard was silent (the other being that scan.sh detects
# comment KINDS, which is what density.sh was added to complement).
#
# The fix is scoping, not deleting the exemption: `.claude/settings.json` should still
# be exempt when it sits in a worktree. So the exclusion test runs against a LOGICAL
# path with any worktree prefix stripped — inside a worktree, a file is judged by where
# it sits in the checkout, exactly as the same file would be judged in the main tree.
#
# LIMITATION (honest scope): the `.claude/worktrees/<name>/` shape is a convention this
# marketplace states, not one git enforces. A worktree placed anywhere else was never
# excluded and is unaffected; a worktree placed at `.claude/wt/<name>` would still be
# skipped, and nothing here can detect that without probing the filesystem for a `.git`
# file on every edit, which is a cost this hook does not want on its hot path.

# cd_logical_path <path> — prints the path with every leading
# `…/.claude/worktrees/<name>/` segment removed, so exclusion patterns see the
# checkout-relative shape. Loops: a worktree checked out inside a worktree is
# unusual but the nesting is what the pattern would otherwise trip on.
cd_logical_path() {
  local p="$1" rest
  while :; do
    case "$p" in
      */.claude/worktrees/*/*)
        rest="${p#*/.claude/worktrees/}"   # <name>/<rest>
        rest="${rest#*/}"                  # <rest>
        [ -n "$rest" ] || break
        p="/$rest"
        ;;
      *) break ;;
    esac
  done
  printf '%s\n' "$p"
}

# scripts/, templates/ and plugins/*/hooks/ are tooling in a marketplace and product code anywhere else.
cd_path_exempt() {
  local lp rel="" root="${2%/}" p="$1" d tail
  lp=$(cd_logical_path "$1")
  case "$lp" in
    */.claude/*|*/node_modules/*|*/vendor/*|*/dist/*|*/.git/*) return 0 ;;
  esac
  [ -n "$2" ] || return 1
  case "$p" in
    "$root"/*) ;;
    */build/*|*/scripts/*.sh|*/templates/*|*/plugins/*/hooks/*)
      # A symlinked spelling (/tmp vs /private/tmp) hides a path that is under the root; the directory may not exist yet.
      d="${p%/*}"; tail="/${p##*/}"
      while [ ! -d "${d:-/}" ]; do case "$d" in */*) tail="/${d##*/}$tail"; d="${d%/*}" ;; *) return 1 ;; esac; done
      d=$(CDPATH= cd -- "${d:-/}" 2>/dev/null && pwd -P) && root=$(CDPATH= cd -- "$root" 2>/dev/null && pwd -P) || return 1
      p="${d%/}$tail" ;;
  esac
  case "$p" in
    "$root"/*) rel=$(cd_logical_path "/${p#"$root"/}"); rel="${rel#/}" ;;
    *) return 1 ;;
  esac
  case "$rel" in build/*) return 0 ;; esac
  [ -f "$root/.claude-plugin/marketplace.json" ] || return 1
  case "$lp" in
    */scripts/*.sh|*/templates/*|*/plugins/*/hooks/*) return 0 ;;
  esac
  return 1
}

# Anchored after the comment leader: a bare "generated by" substring would exempt any file that mentions a generator.
cd_generated() {
  awk 'NR > 5 { exit }
    { s = tolower($0)
      if (NR == 1) sub(/^\357\273\277/, "", s)   # UTF-8 BOM
      if (index(s, "<auto-generated") || index(s, "@generated")) { f = 1; exit }
      sub(/^[ \t\/*#;<!"\047-]+/, "", s)
      if (s ~ /^(code generated|generated by|generated from|generated code|auto-generated|autogenerated|automatically generated|do not edit|do not modify)/ ||
          s ~ /^this (file|code) (is|was) (generated|auto-generated|autogenerated|automatically generated)/) { f = 1; exit } }
    END { exit !f }'
}

# A cd inside a heredoc body or a quoted string is text and moves nothing, unless eval or sh -c may run the string; a `<<` that is quoted, escaped or inside $(( may open no body at all, so then the bodies count too.
cd_has_cd() {
  printf '%s\n' "$1" | awk '
    function unq(s,   i, c, q, out) {
      q = ""; out = ""
      for (i = 1; i <= length(s); i++) {
        c = substr(s, i, 1)
        if (q == "") {
          if (c == "\\") { out = out c substr(s, ++i, 1); continue }
          if (c == "\"" || c == "\047") q = c
          out = out c
        } else if (c == q) { q = ""; out = out c }
        else { if (q == "\"" && c == "\\") { out = out " "; i++ } out = out " " }
      }
      return out
    }
    BEGIN { w = "(^|[^A-Za-z0-9_./-])(cd|chdir|pushd|popd)([^A-Za-z0-9_./-]|$)"
            sh = "(^|[^A-Za-z0-9_.-])(eval|(ba)?sh[ \t]+-[A-Za-z]*c)([^A-Za-z0-9_-]|$)" }
    $0 ~ w { any = 1 }
    inh { if ($0 ~ ("^[\t]*" term "[ \t]*$")) inh = 0; next }
    { l = $0; gsub(/<<</, "", l); o = "<<-?[ \t]*[\"\047\\\\]?"
      m = (l ~ /["\047]/) ? unq(l) : l
      if (l ~ w) raw = 1
      if (m ~ w) bare = 1
      if (l ~ sh) runs = 1
      p = 0
      while ((i = index(substr(l, p + 1), "<<")) > 0) {
        p += i
        if (substr(m, p, 2) != "<<" || substr(l, p - 1, 1) == "\\") loose = 1
        p++
      }
      if ((i = index(l, "$((")) && index(substr(l, i), "<<")) loose = 1
      if (match(l, o "[A-Za-z_][A-Za-z0-9_]*")) { term = substr(l, RSTART, RLENGTH); sub(o, "", term); inh = 1 } }
    END { exit !((runs ? raw : bare) || loose && any) }'
}

# Status 1 skips the target: a miss, never a wrong file. `..` collapses textually unless it steps out of a symlink; the path is left in cd_path so a loop can resolve without a subshell.
cd_resolve() {
  local p="$1" a
  case "$p" in
    /*) ;;
    "~/"*) [ -n "${HOME:-}" ] || return 1; p="$HOME/${p#??}" ;;
    "~"*) return 1 ;;
    *) [ -n "$2" ] && [ "$3" = 0 ] || return 1
       p="$2/$p" ;;
  esac
  while :; do
    case "$p" in
      *//*) p="${p%%//*}/${p#*//}" ;;
      */./*) p="${p%%/./*}/${p#*/./}" ;;
      /../*|*/..) return 1 ;;
      */../*) a="${p%%/../*}"; [ -L "$a" ] && return 1; p="${a%/*}/${p#*/../}" ;;
      *) break ;;
    esac
  done
  cd_path=$p
}

cd_bash_target() { cd_resolve "$@" && printf '%s\n' "$cd_path"; }

# Only a heredoc that cat or tee carries to the file lands there as written: cat with an operand ignores it, and every later pipe stage must be tee; a header after `&&` arrives with a leading space.
cd_chunk_mode() {
  local w head stage n rest="$1|" first=1 sq="'" word redirs re
  word="(\"[^\"]*\"|$sq[^$sq]*$sq|[^[:space:]<>&\"$sq])+"
  redirs="^([[:space:]]*[0-9]*(<<-?|>>|>&|[<>]|&>)[[:space:]]*$word|[[:space:]]+-)*[[:space:]]*(&[[:space:]]*)?(#.*)?\$"
  re='(^|[^0-9&>])>>|(^|[[:space:]|])tee[[:space:]]([^|]*[[:space:]])?(-[A-Za-z]*a[A-Za-z]*|--append)([[:space:]|]|$)'
  while [ -n "$rest" ]; do
    # The first word is read from a bounded prefix: bash 3.2 pattern removal over a 200 kB header takes seconds.
    head="${rest:0:256}"; head="${head%%|*}"; n=${#head}
    while :; do
      head="${head#"${head%%[![:space:]]*}"}"
      w="${head%%[[:space:]<>]*}"
      case "$w" in sudo|[A-Za-z_]*=*) head="${head#"$w"}" ;; *) break ;; esac
    done
    case "$first$w" in 1cat|[01]tee) first=0 ;; *) return 1 ;; esac
    stage="${rest%%|*}"; rest="${rest:$(( ${#stage} + 1 ))}"
    if [ "$w" = cat ]; then [[ "${stage:$(( n - ${#head} + 3 ))}" =~ $redirs ]] || return 1; fi
  done
  if [[ "$1" =~ $re ]]; then printf 'append\n'; else printf 'truncate\n'; fi
}

# A quote glued to the target, or text after its closing quote, makes the shell write a longer name; an escaped name is not the one a Write would key.
cd_target_whole() {
  local r q
  case "$2" in *\\*) return 1 ;; esac
  r="${1#*"$2"}"
  case "$r" in
    [\"\']*) q=$(( ${#1} - ${#r} - ${#2} - 1 ))
             [ "$q" -ge 0 ] && [ "${1:$q:1}" = "${r:0:1}" ] || return 1
             r="${r:1}" ;;
  esac
  case "$r" in ''|[[:space:]\;\&\|\<\>\(\)]*) return 0 ;; esac
  return 1
}

# One awk pass per chunk: appending body lines to a bash string is quadratic.
cd_chunk_text() {
  printf '%s\n' "$1" | awk -v k="$2" 'substr($0, 1, 1) == "\036" { n++; next } n == k'
}
