#!/bin/bash
# Absolute-path shebang not `/usr/bin/env bash`: the fail-open guarantee must hold
# even under a stripped PATH where `env bash` exits 127.
# comment-discipline guard. On an Edit/Write/MultiEdit or a Bash cat/tee heredoc it inspects only the *added* text
# and reports the high-confidence noise patterns. Silence is the common case.
#
# ONE DETECTOR, TWO LANES — the event decides which:
#
#   PostToolUse (default when no event name is present) — WARN. Emits
#   {"hookSpecificOutput":{"hookEventName":"PostToolUse","additionalContext":...}}, exit 0
#   — the one non-blocking channel the executing model actually receives; plain stdout
#   text with exit 0 never reaches it (same reasoning as task-runner/hooks/scope.sh).
#   `additionalContext` is NOT a blocking key: it adds context, it cannot veto. This lane
#   never blocks anything, ever.
#
#   PreToolUse — DENY, narrowly. Warning after the write is warning about a file that is
#   already on disk, and a warning the model may read and walk past is not enforcement.
#   So the three strictest categories — a comment restating the next line, commented-out
#   code, and a docblock tag that repeats the signature — are denied BEFORE the write,
#   and only those. The third joined on 2026-09-02: `@param $id The id` / `@return void`
#   is a syntax match with no prose judgment in it, and it was the shape most of the
#   observed noise took (a full PHPDoc block per method, every tag filled in). Banners,
#   bare TODOs and change-narration comments stay warn-only: they are house-style calls,
#   a TODO can be a legitimate mid-task marker, and narration cues are phrase matches
#   that can catch a legitimate why-comment phrased as a change event.
#
# BOUNDED: the deny fires AT MOST TWICE PER FILE PER SESSION. A third edit to the same file
# goes through and the PostToolUse lane warns instead, so a false positive costs at most two
# extra turns and can never wedge a session. The bound was one until 2026-09-15, when a
# sibling hook denying the same call was found to spend it with no write ever landing. Without a session_id the bound cannot be enforced, so the
# deny is withheld entirely. Generated files (a `@generated` / `generated by` / `do not
# edit` marker in the first five added lines) are exempt, as are the paths and extensions
# already excluded below.
#
# BASH LANE — a `cat`/`tee` heredoc body is judged as a Write of that text to that path
# (cc_bash_write_chunks, cd_bash_target in hooks/paths.sh), chunks in command order, first verdict
# printed. Measured: rationale/2026-09-25-session-plugin-usage-review.md finding 1, 233 of 238 writes.
# NOT SEEN on Bash: interpreter writes (python open()), a heredoc fed to anything but cat/tee,
# echo/printf content, sed -i / perl -i content, cp/mv, a path held in a variable, a relative
# target after an in-command cd, the second operand of `tee a b`, `VAR=x tee f`, cat/tee behind a
# wrapper, brace or keyword (`/bin/cat`, `command cat`, `env X=1 cat`, `(cat`, `{ cat`, `then cat`,
# `sudo -E tee`); plus what the two blocks below say they miss.
#
# Fail-open throughout: a missing jq/awk, or any error, exits 0 and denies nothing.
# CC_REMIND / CC_COMMENT_GUARD unset: the /config options cc_remind / cc_comment_guard decide.
# Deny markers: per project under CLAUDE_PLUGIN_DATA (cc_plugin_state); <root>/.claude/comment-discipline/ is only the fallback.

# --- state root ----------------------------------------------------------------
# Canonical copy: templates/blocks/state-root.md. Every hook defining cc_state_root must
# carry this block byte-for-byte (pc_shared_blocks); generated hooks include it.
# The payload's `cwd` is the SHELL's cwd and follows the model's `cd` — measured
# 2026-09-25: app/Enums, then app/Models, then the repo root in one session, each leaving
# its own `.claude/` state dir and each re-firing a "once per session" nudge. State lives
# at the project root instead (pc_state_root refuses a raw `$cwd/.claude` path in a hook):
# the git toplevel reached by walking UP from cwd (`--show-cdup`, so a symlinked /tmp keeps
# the caller's spelling and path-prefix comparisons still hold); outside git,
# CLAUDE_PROJECT_DIR when cwd sits under it; else cwd. A cwd that no longer exists yields
# nothing and status 1 — the caller exits rather than resurrect a deleted project.
cc_state_root() {
  [ -n "$1" ] && [ -d "$1" ] || return 1
  local up pd="${CLAUDE_PROJECT_DIR:-}"; pd="${pd%/}"
  if up=$(git -C "$1" rev-parse --show-cdup 2>/dev/null); then
    [ -n "$up" ] || { printf '%s\n' "$1"; return 0; }
    (CDPATH= cd -- "$1/$up" 2>/dev/null && pwd) && return 0
  fi
  if [ -n "$pd" ] && [ -d "$pd" ]; then
    case "$1/" in "$pd"/*) printf '%s\n' "$pd"; return 0 ;; esac
  fi
  printf '%s\n' "$1"
}

# --- plugin state --------------------------------------------------------------
# Canonical copy: templates/blocks/plugin-state.md. Every hook defining cc_plugin_state must
# carry this block byte-for-byte (pc_shared_blocks); generated hooks include it.
# cc_plugin_state <root> <name> prints the directory holding a plugin's own per-project hook
# state, <root> being the hook's cc_state_root result: ${CLAUDE_PLUGIN_DATA}/<key>/<name> when
# the host sets that variable, else <root>/.claude/<name>, the path hooks used before it.
# <key> is the root's basename with every character outside [A-Za-z0-9_-] turned into -, a -,
# and the root's cksum: the host gives one data dir per plugin id, not per project (measured
# 2.1.282), and a raw path inside a filename names parents that never exist. tr runs under
# LC_ALL=C because a UTF-8 tr stops at the first invalid byte. Status 0, no stderr; it
# creates nothing, so the caller keeps its own mkdir -p.
# WHY: state read by no one but the plugin's own hooks does not belong in the user's repo —
# the 2026-09-29 review found .claude/code-review/ and .claude/skill-router/ created by one
# prompt and one edit in a fresh repo.
# WHAT IT DOES NOT CATCH: state another plugin, a skill or the user reads must not use it; the
# fallback path is still in the repo; the data dir is keyed by plugin id, so install scopes of
# one plugin share it (inferred from the docs' id rule), while a --plugin-dir copy gets its
# own `-inline` directory and never sees the installed copy's state. The variable was measured
# only in a SessionStart hook; other events are doc-stated. An event that lacks it falls back
# to the repo path, which splits a writer from a reader running on another event.
cc_plugin_state() {
  local key sum
  if [ -n "${CLAUDE_PLUGIN_DATA:-}" ]; then
    key=$(printf '%s' "$(basename -- "$1")" | LC_ALL=C tr -c 'A-Za-z0-9_-' '-')
    sum=$(printf '%s' "$1" | cksum | cut -d' ' -f1)
    printf '%s/%s-%s/%s\n' "${CLAUDE_PLUGIN_DATA%/}" "$key" "$sum" "$2"
  else
    printf '%s/.claude/%s\n' "$1" "$2"
  fi
  return 0
}

# --- option resolver -----------------------------------------------------------
# Canonical copy: templates/blocks/option-resolver.md. Every hook defining cc_option must
# carry this block byte-for-byte (pc_shared_blocks); generated hooks include it.
# cc_option <ENV_NAME> <default> [<level-file>] prints one line, the first non-empty of: the
# variable ENV_NAME; the first word of <level-file>, if given and readable; the userConfig
# option CLAUDE_PLUGIN_OPTION_<ENV_NAME>, true/false read as on/off; <default>. The shell wins
# because the environment is the one state independently installed plugins share (CC_REMIND
# or CC_BOOST there mutes every plugin at once); the option gives one plugin a /config row.
# The host exports only SAVED options, so <default> must equal the manifest's default.
# Status 0, no stderr: a malformed name, an expansion error that exits bash 5, yields <default>.
# WHAT IT DOES NOT CATCH: a caller passing a variable instead of a literal name, or a value
# outside the switch's vocabulary — each hook still validates the value it gets.
cc_option() {
  local v="" opt
  case "${1:-}" in '' | [0-9]* | *[!A-Za-z0-9_]*) printf '%s\n' "${2:-}"; return 0 ;; esac
  v="${!1:-}"
  if [ -z "$v" ] && [ -n "${3:-}" ] && [ -f "$3" ] && [ -r "$3" ]; then
    read -r v _ 2>/dev/null < "$3" || :
  fi
  if [ -z "$v" ]; then
    opt="CLAUDE_PLUGIN_OPTION_$1"; v="${!opt:-}"
    case "$v" in true) v=on ;; false) v=off ;; esac
  fi
  [ -n "$v" ] || v="${2:-}"
  printf '%s\n' "$v"
  return 0
}

# --- bash write targets --------------------------------------------------------
# Canonical copy: templates/blocks/bash-write-targets.md. Every hook defining
# cc_bash_write_targets must carry this block byte-for-byte (pc_shared_blocks).
# The host steers file writes through Bash (auto mode `bashFirst`); in one measured session
# 233 of 238 main-thread writes were `cat > file <<EOF`, invisible to a hook matching
# Write|Edit.
# Prints one target path per line, as spelled in the command (relative or absolute).
# Heredoc BODIES are dropped and quoted text is masked before matching, so PHP `->`/`=>`,
# HTML `>` and a sed script's `s|a|b|` never read as redirects or pipes; a here-string
# (`<<<`) is not a heredoc. Catches `>`/`>>` onto a path (cat, echo, printf, any command),
# `[sudo] tee [-a] <paths>`, and every file operand of `sed -i`/`-I`/`--in-place` / `perl -i`
# after the script or its `-e`/`-f` arguments, never a redirect word or its target. BSD's
# `-I` always takes the next word as its backup suffix; a `''` or a `.`-led word with no `/`
# right after sed's bare `-i` is read as one too, unless it would be the only file.
# Does NOT catch:
# interpreter writes (python open(), php file_put_contents), cp/mv/install destinations,
# `{ …; } > f` groups, a path held in a variable (`> "$f"` is skipped, never guessed),
# a globbed operand (`sed -i … tests/*.js`: a word with `*`/`?` is dropped), a `\` line
# continuation, sed/perl behind another command word (`gsed`, `/usr/bin/sed`, `env`,
# `xargs`, `command`, `sudo -u x`, `find … -exec sed -i`), a digit- or `&`-led redirect onto
# a file (`2> f`, `&> f`). A lone `&` does not end a command, so words after it can read as
# sed/perl/tee operands.
# The caller filters to existing files under its root.
cc_bash_write_targets() {
  printf '%s\n' "$1" | awk '
    function emit(p) {
      gsub(/^["\047]|["\047]$/, "", p)
      if (p == "" || p ~ /^\/dev\// || p ~ /[$`*?]/ || p ~ /^[&0-9-]/ && p !~ /[\/.]/) return
      print p
    }
    function mask(s,   i, c, q, out, esc) {
      q = ""; out = ""; esc = 0
      for (i = 1; i <= length(s); i++) {
        c = substr(s, i, 1)
        if (esc) { out = out "_"; esc = 0; continue }
        if (q == "") {
          if (c == "\\") { esc = 1; out = out "_"; continue }
          if (c == "\047" || c == "\"") q = c
          out = out c
        } else if (c == q) { q = ""; out = out c }
        else { if (q == "\"" && c == "\\") esc = 1; out = out "_" }
      }
      return out
    }
    function segment(ms, os,   rest, off, tok, w, k, j, st, en, word, n, ws, we, x, c, a, inp, scr, eo, sfx, nf, f) {
      rest = ms; off = 0
      while (match(rest, /(^|[^0-9&=<>-])>>?[ \t]*("[^"]*"|\047[^\047]*\047|[^ \t&|;<>()"\047]+)/)) {
        tok = substr(os, off + RSTART, RLENGTH)
        off += RSTART + RLENGTH - 1; rest = substr(ms, off + 1)
        sub(/^[^>]*>>?[ \t]*/, "", tok)
        emit(tok)
      }
      n = 0; j = 1
      while (j <= length(ms)) {
        while (j <= length(ms) && substr(ms, j, 1) ~ /[ \t]/) j++
        if (j > length(ms)) break
        st = j; while (j <= length(ms) && substr(ms, j, 1) !~ /[ \t]/) j++
        n++; ws[n] = st; we[n] = j - 1
      }
      if (n == 0) return
      k = 1; word = substr(os, ws[1], we[1] - ws[1] + 1)
      if (word == "sudo" && n > 1) { k = 2; word = substr(os, ws[2], we[2] - ws[2] + 1) }
      if (word == "tee") {
        for (k = k + 1; k <= n; k++) {
          w = substr(os, ws[k], we[k] - ws[k] + 1)
          if (w == "<" || w == "<<<") { k++; continue }
          if (w !~ /^-/ && w !~ /^[<>0-9]/) emit(w)
        }
      } else if (word == "sed" || word == "perl") {
        inp = 0; scr = 0; eo = 0; sfx = ""; nf = 0
        for (k = k + 1; k <= n; k++) {
          w = substr(os, ws[k], we[k] - ws[k] + 1); x = substr(ms, ws[k], we[k] - ws[k] + 1)
          if (x ~ /[<>]/) {
            a = substr(w, 1, match(x, /[<>]/) - 1)
            if (a !~ /^[0-9&]*$/) f[++nf] = a
            if (x ~ /[<>][&|]?$/) k++
            continue
          }
          if (eo || x !~ /^-./) { f[++nf] = w; if (word == "perl") eo = 1; continue }
          if (x == "--") { eo = 1; continue }
          if (x ~ /^--/) {
            if (word == "sed" && x ~ /^--in-place(=|$)/) inp = 1
            if (word == "sed" && x ~ /^--(expression|file)(=|$)/) { scr = 1; if (x !~ /=/) k++ }
            continue
          }
          for (j = 2; j <= length(x); j++) {
            c = substr(x, j, 1)
            if (c == "i" || word == "sed" && c == "I") {
              inp = 1
              if (word == "sed" && j == length(x) && k < n) {
                a = substr(os, ws[k + 1], we[k + 1] - ws[k + 1] + 1); gsub(/^["\047]|["\047]$/, "", a)
                if (c == "I") k++
                else if (a == "" || a ~ /^\.[^\/<>]*$/) { k++; sfx = a }
              }
              break
            }
            if (c == "e" || c == (word == "sed" ? "f" : "E")) { scr = 1; if (j == length(x)) k++; break }
            if (c == (word == "sed" ? "l" : "I")) { if (j == length(x)) k++; break }
            if (word == "perl" && c ~ /[MmFxdDVC]/) break
            if (word == "perl" && c ~ /[l0]/) while (substr(x, j + 1, 1) ~ /[0-7]/) j++
          }
        }
        if (!inp) return
        for (j = scr ? 1 : 2; j <= nf; j++) if (f[j] !~ /^-/) { emit(f[j]); sfx = "" }
        if (sfx != "") emit(sfx)
      }
    }
    skip { t = $0; sub(/^[ \t]+/, "", t); sub(/[ \t]+$/, "", t); if (t == term) skip = 0; next }
    {
      line = $0; m = mask(line)
      if (match(m, /(^|[^<])<<-?[ \t]*["\047]?[A-Za-z_][A-Za-z0-9_]*/)) {
        if (substr(m, RSTART, 1) != "<") { RSTART++; RLENGTH-- }
        term = substr(line, RSTART, RLENGTH + 1)
        sub(/^<<-?[ \t]*["\047]?/, "", term); sub(/[^A-Za-z0-9_].*$/, "", term)
        skip = 1
      }
      st = 1
      for (i = 1; i <= length(m) + 1; i++) {
        c = substr(m, i, 1); c2 = substr(m, i, 2)
        if (i > length(m) || c == ";" || c == "|" || c2 == "&&") {
          if (i > st) segment(substr(m, st, i - st), substr(line, st, i - st))
          if (c2 == "&&" || c2 == "||") i++
          st = i + 1
        }
      }
    }' | awk '!seen[$0]++'
}

# --- bash write chunks --------------------------------------------------------
# Canonical copy: templates/blocks/bash-write-chunks.md. Every hook defining
# cc_bash_write_chunks must carry this block byte-for-byte (pc_shared_blocks).
# cc_bash_write_chunks <command> — what a Bash command puts INTO files: the text a content
# guard reads on Bash where its Write path reads tool_input.content. Prints chunks: a line that
# starts with \036 and carries the WRITER — the pipeline (split on ; && ||, never inside
# quotes) whose targets the caller resolves with cc_bash_write_targets — then the
# chunk's text lines. Two sources, and only two:
#   - a heredoc BODY: the lines between `<<TERM` (`<<-`, quoted or `\`-escaped TERM too)
#     and TERM; writer = the pipeline holding the `<<` (`cat > f <<EOF`,
#     `cat <<EOF | tee -a f`);
#   - the ARGUMENTS of an `echo`/`printf` segment, as written: the rest of the segment after
#     the command word, quotes, escapes and any `> file` redirect kept (so match inside the
#     text, never anchored at its start); writer = its pipeline
#     (`echo "K=v" >> .env.example`, `printf '%s\n' v | tee f`).
# A chunk whose writer names no file is dropped by the caller, so `git commit -F - <<EOF`
# and `echo x | grep y` yield nothing. The body of ANY heredoc whose pipeline writes a file
# is read, whatever consumes it — `python3 - <<PY > out.txt` included, where the script is
# not what lands in out.txt. Accepted: the text sits in a file-writing command either
# way.
# NOT read, stated: a `{ echo …; } > f` group (the redirect sits on the closer, not on
# the echo's pipeline); a here-string `<<<`; printf's format substitution (`printf
# 'K=%s' v` is read as written: the format and the argument, never the substituted
# line); a quoted string or a `\` continuation spanning lines; a second heredoc opened
# on one line.
# mask() copies the one inside cc_bash_write_targets: the block is byte-locked and its
# awk functions are not reachable from outside it.
cc_bash_write_chunks() {
  printf '%s\n' "$1" | awk '
    function mask(s,   i, c, q, out, esc) {
      q = ""; out = ""; esc = 0
      for (i = 1; i <= length(s); i++) {
        c = substr(s, i, 1)
        if (esc) { out = out "_"; esc = 0; continue }
        if (q == "") {
          if (c == "\\") { esc = 1; out = out "_"; continue }
          if (c == "\047" || c == "\"") q = c
          out = out c
        } else if (c == q) { q = ""; out = out c }
        else { if (q == "\"" && c == "\\") esc = 1; out = out "_" }
      }
      return out
    }
    function trim(s) { sub(/^[ \t]+/, "", s); sub(/[ \t]+$/, "", s); return s }
    function echo_args(p, mp,   i, st, seg, out) {
      out = ""; st = 1
      for (i = 1; i <= length(mp) + 1; i++) {
        if (i > length(mp) || substr(mp, i, 1) == "|") {
          seg = substr(mp, st, i - st)
          if (match(seg, /^[ \t]*(echo|printf)[ \t]/)) out = out substr(p, st + RLENGTH, i - st - RLENGTH) "\n"
          st = i + 1
        }
      }
      return out
    }
    inbody { if (trim($0) == term) inbody = 0; else print; next }
    {
      line = $0; m = mask(line); st = 1; opener = ""
      for (i = 1; i <= length(m) + 1; i++) {
        c = substr(m, i, 1); c2 = substr(m, i, 2)
        if (i > length(m) || c == ";" || c2 == "&&" || c2 == "||") {
          if (i > st) {
            p = substr(line, st, i - st); mp = substr(m, st, i - st)
            a = echo_args(p, mp)
            if (a != "") printf "\036%s\n%s", p, a
            if (opener == "" && match(mp, /(^|[^<])<<-?[ \t]*["\047]?[A-Za-z_][A-Za-z0-9_]*/)) {
              t = substr(p, RSTART, RLENGTH)
              sub(/^[^<]*<<-?[ \t]*["\047]?/, "", t); sub(/^\\/, "", t); sub(/[^A-Za-z0-9_].*$/, "", t)
              if (t != "") { opener = p; term = t }
            }
          }
          if (c2 == "&&" || c2 == "||") i++
          st = i + 1
        }
      }
      if (opener != "") { printf "\036%s\n", opener; inbody = 1 }
    }'
}

{
  command -v jq  >/dev/null 2>&1 || exit 0
  command -v awk >/dev/null 2>&1 || exit 0

  input=$(cat)
  # One detector, two lanes. Absent event name = PostToolUse, the original behavior.
  event=$(printf '%s' "$input" | jq -r '.hook_event_name // "PostToolUse"' 2>/dev/null) || exit 0
  tool=$(printf '%s' "$input" | jq -r '.tool_name // empty' 2>/dev/null) || exit 0
  case "$tool" in
    Edit|Write|MultiEdit) ;;
    Bash)
      cmd=$(printf '%s' "$input" | jq -r '.tool_input.command // empty' 2>/dev/null) || exit 0
      # The blocks mask a line character by character, quadratic in its length: a 200 kB line, or 100 lines of 8 kB, outlasts the timeout, so such a command is not judged.
      [ "${#cmd}" -gt 32768 ] && printf '%s\n' "$cmd" | awk 'length($0) > 2000 { s += length($0) } length($0) > 8192 || s > 32768 { f = 1; exit } END { exit !f }' && exit 0
      [ -n "$(cc_bash_write_targets "$cmd")" ] || exit 0 ;;
    *) exit 0 ;;
  esac
  cwd=$(printf '%s' "$input" | jq -r '.cwd // empty' 2>/dev/null)
  # CC_REMIND is the marketplace-wide advisory switch, and the README promised it here
  # for two releases while nothing read it. It silences the WARN lane only: a PreToolUse
  # deny is not an advisory, so an env var must not be able to turn a block into a pass.
  [ "$event" = "PostToolUse" ] && [ "$(cc_option CC_REMIND on)" = "off" ] && exit 0
  # CC_COMMENT_GUARD=off disables the DENY lane and leaves the advisory lane on.
  # Added 2026-09-22 (UX 1): until now the block had no off switch at all — CC_REMIND
  # covers the advisory only — so the refusal could name none, which is what
  # pc_offswitch_named reports. Read from the hook's environment, which the edit text
  # cannot reach. Two lanes, two switches: silencing the block keeps the finding visible.
  [ "$event" = "PreToolUse" ] && [ "$(cc_option CC_COMMENT_GUARD on)" = "off" ] && exit 0

  # Code only. Config and prose formats use comments for navigation, which this rule
  # does not govern — so YAML stays OUT deliberately, including docker-compose.yml,
  # CI workflows and k8s manifests, where a `# the web service` header is a real
  # navigation aid rather than a restatement.
  #
  # BUILD FILES ARE CODE, and that is why they are in. A Dockerfile and a Makefile are
  # imperative step lists, not documents: `# install dependencies` above
  # `RUN apt-get install -y …` restates its next line exactly the way `// increment the
  # counter` does above `counter++`, and *.sh has always been governed for that reason.
  # Extensionless names are matched by basename, so the worktree-stripped path is not
  # enough on its own — see the `base` case below.
  scan_governed() {
    case "$1" in
      *.js|*.jsx|*.ts|*.tsx|*.mjs|*.cjs|*.vue|*.svelte) ;;
      *.php|*.py|*.rb|*.go|*.rs|*.java|*.kt|*.kts|*.swift|*.scala|*.dart) ;;
      *.c|*.h|*.cpp|*.hpp|*.cc|*.cs|*.m|*.mm) ;;
      *.sh|*.bash|*.zsh|*.pl|*.lua|*.ex|*.exs|*.jl|*.r|*.groovy) ;;
      *.sql|*.css|*.scss|*.less|*.graphql|*.tf) ;;
      *.dockerfile|*.mk) ;;
      *)
        case "$(basename "$1")" in
          Dockerfile|Dockerfile.*|Containerfile|Containerfile.*|Makefile|GNUmakefile) ;;
          *) return 1 ;;
        esac ;;
    esac
  }

  scan_judge() {
  fp=$1 added=$2 msg=""
  [ -n "$fp" ] || return 1
  scan_governed "$fp" || return 1

  # Generated, vendored, and marketplace tooling paths are exempt: their header banners and
  # usage blocks are deliberate, and nobody edits them by hand for readability.
  #
  # Tested against the LOGICAL path — a worktree prefix stripped — because this
  # marketplace places worktrees at `.claude/worktrees/<branch>`, and `*/.claude/*`
  # was therefore exempting every source file written by a track run. See
  # hooks/paths.sh. A missing lib exits 0: a path it cannot classify is not judged.
  root=$(cc_state_root "$cwd") || root=""   # no root is not a marketplace: the file is still judged
  . "$(dirname "$0")/paths.sh" 2>/dev/null
  command -v cd_path_exempt >/dev/null 2>&1 || return 1
  cd_path_exempt "$fp" "$root" && return 1

  [ -n "$added" ] || return 1

  raw=$(printf '%s\n' "$added" | awk '
  function add_tok(set, w,   x) {
    if (w == "") return
    x = tolower(w)
    if (length(x) < 2) return
    set[x] = 1
    if (length(x) > 3 && substr(x, length(x)) == "s") set[substr(x, 1, length(x) - 1)] = 1
  }
  # camelCase and snake_case carry the same words a comment would spell out, so a name
  # only counts as "already says it" once it is split back into those words.
  function split_ident(w, set,   i, c, cur) {
    cur = ""
    for (i = 1; i <= length(w); i++) {
      c = substr(w, i, 1)
      if (c == "_" || c == "$" || c == "-") { add_tok(set, cur); cur = ""; continue }
      if (c ~ /[A-Z]/ && cur != "" && substr(cur, length(cur)) ~ /[a-z0-9]/) {
        add_tok(set, cur); cur = c; continue
      }
      cur = cur c
    }
    add_tok(set, cur)
  }
  function code_tokens(l, set,   n, arr, i, w) {
    n = split(l, arr, /[^A-Za-z0-9_$]+/)
    for (i = 1; i <= n; i++) {
      w = arr[i]
      if (w == "") continue
      add_tok(set, w)
      split_ident(w, set)
    }
  }
  # Operators say in symbols what a restating comment says in words; without this map
  # "// increment the counter" over "counter++" reads as new information.
  function op_tokens(l, set) {
    if (l ~ /\+\+/)   { add_tok(set, "increment"); add_tok(set, "increase"); add_tok(set, "bump"); add_tok(set, "count") }
    if (l ~ /--/)     { add_tok(set, "decrement"); add_tok(set, "decrease"); add_tok(set, "subtract") }
    if (l ~ /\+=/)    { add_tok(set, "add"); add_tok(set, "increment"); add_tok(set, "append"); add_tok(set, "increase") }
    if (l ~ /-=/)     { add_tok(set, "subtract"); add_tok(set, "decrease") }
    if (l ~ /=/)      { add_tok(set, "set"); add_tok(set, "assign"); add_tok(set, "store"); add_tok(set, "save"); add_tok(set, "update"); add_tok(set, "initialize"); add_tok(set, "init"); add_tok(set, "define"); add_tok(set, "declare"); add_tok(set, "value") }
    if (l ~ /(^|[^A-Za-z])return([^A-Za-z]|$)/) { add_tok(set, "return"); add_tok(set, "result"); add_tok(set, "output"); add_tok(set, "give") }
    if (l ~ /(^|[^A-Za-z])if([^A-Za-z]|$)/)     { add_tok(set, "check"); add_tok(set, "handle"); add_tok(set, "test") }
    if (l ~ /(^|[^A-Za-z])(for|while|forEach|foreach|map)([^A-Za-z]|$)/) { add_tok(set, "loop"); add_tok(set, "iterate"); add_tok(set, "over"); add_tok(set, "through"); add_tok(set, "every") }
    if (l ~ /(^|[^A-Za-z])new([^A-Za-z]|$)/)    { add_tok(set, "create"); add_tok(set, "make"); add_tok(set, "instantiate"); add_tok(set, "build"); add_tok(set, "construct") }
    if (l ~ /(^|[^A-Za-z])(throw|raise)([^A-Za-z]|$)/) { add_tok(set, "throw"); add_tok(set, "raise"); add_tok(set, "error"); add_tok(set, "fail") }
    if (l ~ /(^|[^A-Za-z])(delete|remove|unset|splice|drop)([^A-Za-z]|$)/) { add_tok(set, "delete"); add_tok(set, "remove"); add_tok(set, "drop"); add_tok(set, "clear") }
    if (l ~ /(^|[^A-Za-z])(push|append|insert|add)([^A-Za-z]|$)/) { add_tok(set, "add"); add_tok(set, "append"); add_tok(set, "insert") }
    if (l ~ /(^|[^A-Za-z])(import|require|include|use)([^A-Za-z]|$)/) { add_tok(set, "import"); add_tok(set, "load"); add_tok(set, "require"); add_tok(set, "include") }
    if (l ~ /(^|[^A-Za-z])(log|print|echo|puts|printf|println)([^A-Za-z]|$)/) { add_tok(set, "log"); add_tok(set, "print"); add_tok(set, "output"); add_tok(set, "debug"); add_tok(set, "write"); add_tok(set, "show") }
    if (l ~ /(^|[^A-Za-z])(await|async)([^A-Za-z]|$)/) { add_tok(set, "wait"); add_tok(set, "await"); add_tok(set, "async") }
    if (l ~ /(^|[^A-Za-z])(try|catch|except|rescue)([^A-Za-z]|$)/) { add_tok(set, "try"); add_tok(set, "catch"); add_tok(set, "handle"); add_tok(set, "error"); add_tok(set, "guard") }
    if (l ~ /(^|[^A-Za-z])(null|nil|None|undefined)([^A-Za-z]|$)/) { add_tok(set, "clear"); add_tok(set, "reset"); add_tok(set, "empty"); add_tok(set, "blank") }
    if (l ~ /(^|[^A-Za-z])true([^A-Za-z]|$)/)  { add_tok(set, "enable"); add_tok(set, "allow"); add_tok(set, "on") }
    if (l ~ /(^|[^A-Za-z])false([^A-Za-z]|$)/) { add_tok(set, "disable"); add_tok(set, "block"); add_tok(set, "off") }
    if (l ~ /(length|count|size)/)  { add_tok(set, "count"); add_tok(set, "length"); add_tok(set, "size"); add_tok(set, "number"); add_tok(set, "total") }
    if (l ~ /sort/)   { add_tok(set, "sort"); add_tok(set, "order"); add_tok(set, "rank") }
    if (l ~ /filter/) { add_tok(set, "filter"); add_tok(set, "keep"); add_tok(set, "select"); add_tok(set, "exclude") }
    if (l ~ /(function|=>|def )/) { add_tok(set, "define"); add_tok(set, "declare"); add_tok(set, "function"); add_tok(set, "helper") }
    if (l ~ /\+/) { add_tok(set, "add"); add_tok(set, "sum"); add_tok(set, "plus"); add_tok(set, "concat"); add_tok(set, "join"); add_tok(set, "combine") }
    if (l ~ /\*/) { add_tok(set, "multiply"); add_tok(set, "times"); add_tok(set, "product") }
    if (l ~ /\//) { add_tok(set, "divide"); add_tok(set, "ratio") }
    if (l ~ /%/)  { add_tok(set, "modulo"); add_tok(set, "remainder") }
    if (l ~ /[<>]/) { add_tok(set, "compare"); add_tok(set, "greater"); add_tok(set, "less"); add_tok(set, "than"); add_tok(set, "exceeds") }
    if (l ~ /(\?\?|\|\|)/) { add_tok(set, "default"); add_tok(set, "fallback") }
  }
  function cbody(l,   s) {
    s = l
    sub(/^[ \t]+/, "", s)
    if (s ~ /^#!/) return ""
    if (s ~ /^\/\//)  { sub(/^\/\/+[ \t]*/, "", s); return s }
    if (s ~ /^\/\*/)  { sub(/^\/\*+[ \t]*/, "", s); sub(/[ \t]*\*\/[ \t]*$/, "", s); return s }
    if (s ~ /^\*/ && s !~ /^\*[A-Za-z0-9_(]/) { sub(/^\*+[ \t]*/, "", s); sub(/[ \t]*\*\/[ \t]*$/, "", s); return s }
    if (s ~ /^#[ \t]/ || s ~ /^##/) { sub(/^#+[ \t]*/, "", s); return s }
    if (s ~ /^-- /)   { sub(/^--[ \t]*/, "", s); return s }
    return ""
  }
  # Legally required, machine-read, or tool-directive comments are not prose anyone
  # chose to write, so they are outside this rule entirely.
  function exempt(b,   x) {
    x = tolower(b)
    if (x ~ /spdx|copyright|all rights reserved|licensed under|license:|licence:/) return 1
    if (x ~ /eslint-|tslint|jshint|ts-expect-error|ts-ignore|@ts-|type: *ignore|noqa|phpcs:|phpstan-|psalm-|prettier-ignore|biome-ignore|stylelint-|pylint:|rubocop:|nolint|golangci|istanbul ignore|c8 ignore|codecoverageignore|shellcheck|coverage:/) return 1
    return 0
  }
  function is_banner(b,   c) {
    if (b !~ /^[=*#_~-][=*#_~-][=*#_~-]/ && b !~ /[=*#_~-][=*#_~-][=*#_~-][ \t]*$/) return 0
    c = b
    gsub(/[^A-Za-z0-9]/, "", c)
    return (length(c) <= 24)
  }
  function is_code(b) {
    if (b ~ /^[})\];]+[ \t]*;?[ \t]*$/) return 1
    if (b ~ /;[ \t]*$/ && b ~ /[=(]/) return 1
    if (b ~ /^(if|for|while|switch|foreach)[ \t]*\(/) return 1
    if (b ~ /^(return|const|let|var|def|class|function|import|export|public|private|protected|echo|print|new|await|async)[ \t]/ && b ~ /[=({:]/) return 1
    if (b ~ /^[A-Za-z_$][A-Za-z0-9_$.]*\(.*\)[ \t]*;?[ \t]*$/) return 1
    if (b ~ /^[$@]?[A-Za-z_][A-Za-z0-9_]*[ \t]*=[^=]/) return 1
    return 0
  }
  # The diff addressing its reviewer: a comment describing the EDIT — its author, its
  # correctness, the review that asked for it — rather than the code. A why-comment
  # states a standing constraint; a change event ("now handles", "updated to", "fix
  # per review") is stale the moment the change merges. Phrase cues, so warn-only.
  # A ticket, issue, or URL rescues the comment outright: a reference to track is the
  # keep-case form ("Retry cap of 5 as discussed in ADR-12"), same idiom as is_bare_todo.
  function is_narration(b,   x) {
    if (b ~ /#[0-9]/ || b ~ /[A-Z][A-Z0-9]+-[0-9]/ || b ~ /https?:\/\//) return 0
    x = tolower(b)
    if (x ~ /^now that /) return 0
    if (x ~ /^(now|it now|this now|we now) /) return 1
    if (x ~ /(^| )now (correctly|properly) /) return 1
    if (x ~ /^(this|the) (fix|change|update|patch|refactor) (is|was|also|now|makes|ensures|addresses|fixes|resolves|prevents|handles|corrects|improves|adds|removes) /) return 1
    if (x ~ /^fix(ed)?(:| for )/) return 1
    if (x ~ /^(added|removed|renamed|moved|corrected|bugfix|hotfix)[ :]/) return 1
    if (x ~ /^fixes /) return 1
    if (x ~ /^no longer /) return 1
    if (x ~ /as requested|per (the )?review|review feedback|as discussed|addresses (the )?(review|comment|feedback)/) return 1
    if (x ~ /^(updated|changed|switched|migrated|converted|refactored|rewrote|reworked) (to|from|this|the) /) return 1
    if (x ~ /^previously,/) return 1
    if (x ~ /used to (be|return|use)/) return 1
    return 0
  }
  function is_bare_todo(b) {
    if (b !~ /TODO|FIXME|XXX|HACK/) return 0
    if (b ~ /#[0-9]/) return 0
    if (b ~ /[A-Z][A-Z0-9]+-[0-9]/) return 0
    if (b ~ /https?:\/\//) return 0
    return 1
  }
  function is_dead_tag(b,   t, n, arr, i, name, desc, seen, d) {
    if (b ~ /^@returns?[ \t]+void[ \t.]*$/) return 1
    if (b ~ /^@returns?[ \t]*$/) return 1
    if (b ~ /^:param[ \t]/) { t = b; sub(/^:param[ \t]+/, "", t); sub(/:/, " ", t) }
    else if (b ~ /^@param[ \t]/) { t = b; sub(/^@param[ \t]+/, "", t) }
    else return 0
    n = split(t, arr, /[ \t]+/)
    name = ""
    for (i = 1; i <= n && i <= 2; i++) if (arr[i] ~ /^\$/) { name = substr(arr[i], 2); break }
    if (name == "" && n >= 2 && arr[1] ~ /^[A-Za-z_|\\{<]/ && arr[2] ~ /^[A-Za-z_]/) name = arr[2]
    if (name == "" && n == 1) name = arr[1]
    if (name == "") return 0
    seen = 0; desc = ""
    for (i = 1; i <= n; i++) {
      if (!seen && (arr[i] == name || arr[i] == ("$" name))) { seen = 1; continue }
      if (seen) desc = desc " " arr[i]
    }
    if (!seen) return 0
    d = tolower(desc)
    gsub(/[.,:]/, "", d)
    gsub(/^[ \t]+|[ \t]+$/, "", d)
    sub(/^(the|a|an)[ \t]+/, "", d)
    if (d == "") return 1
    gsub(/[ \t]/, "", d)
    return (d == tolower(name))
  }
  # Every content word of the comment must already be recoverable from the code line.
  # Requiring ALL of them, not a ratio, is what keeps this warning credible.
  function restates(b, code,   set, n, arr, i, w, ct, sing) {
    split("", set)
    code_tokens(code, set)
    op_tokens(code, set)
    n = split(b, arr, /[^A-Za-z0-9_]+/)
    ct = 0
    for (i = 1; i <= n; i++) {
      w = tolower(arr[i])
      if (w == "" || length(w) < 2) continue
      if (w in SW) continue
      ct++
      if (w in set) continue
      sing = (length(w) > 3 && substr(w, length(w)) == "s") ? substr(w, 1, length(w) - 1) : ""
      if (sing != "" && (sing in set)) continue
      return 0
    }
    return (ct > 0)
  }
  BEGIN {
    split("the a an to to of for and or is are was were be being been this that these those it its we you i they he she then now here there in on on at by with from as into each all any some if so do does did not no our your their and but when while where which who what how new old up down out off over under again very can will would should could may might must has have had", swl, " ")
    for (i in swl) SW[swl[i]] = 1
    split("restating the next line|section banner|commented-out code|bare TODO|docblock tag repeating the signature|change-narration (describes the edit, not the code)", CATS, "|")
  }
  { L[++T] = $0 }
  END {
    for (i = 1; i <= T; i++) {
      b = cbody(L[i])
      if (b == "" || exempt(b)) continue
      if (is_banner(b))       { H[2]++; total++; continue }
      if (is_code(b))         { H[3]++; total++; continue }
      if (is_bare_todo(b))    { H[4]++; total++; continue }
      if (is_dead_tag(b))     { H[5]++; total++; continue }
      if (is_narration(b))    { H[6]++; total++; continue }
      j = i + 1
      while (j <= T && (L[j] ~ /^[ \t]*$/ || cbody(L[j]) != "")) j++
      if (j <= T && restates(b, L[j])) { H[1]++; total++ }
    }
    if (total == 0) exit 0
    # Line 1 is machine-read by the shell: how many findings are in the three
    # BLOCKABLE categories (restatement, commented-out code, dead docblock tag).
    # Those are the strictest detectors here — restates() requires EVERY content
    # word of the comment to be recoverable from the code line, is_code() matches
    # syntax, and is_dead_tag() fires only when the tag description is empty or
    # the parameter name itself. Banners, bare TODOs and change-narration comments
    # stay warn-only: they are house-style calls, a TODO can be a legitimate
    # mid-task marker, and narration cues are phrase matches.
    printf "%d\n", (1 in H ? H[1] : 0) + (3 in H ? H[3] : 0) + (5 in H ? H[5] : 0)
    parts = ""
    for (k = 1; k <= 6; k++) {
      if (!(k in H)) continue
      parts = parts (parts == "" ? "" : ", ") H[k] " " CATS[k]
    }
    printf "comment-discipline: %d added %s (%s) — check the routing table in the comment-discipline skill for where those facts belong.\n", total, (total == 1 ? "comment looks like noise" : "comments look like noise"), parts
  }')
  [ -n "$raw" ] || return 1
  blockable=$(printf '%s\n' "$raw" | head -1)
  warn=$(printf '%s\n' "$raw" | tail -n +2)
  [ -n "$warn" ] || return 1
  case "$blockable" in ''|*[!0-9]*) blockable=0 ;; esac

  if [ "$event" != "PreToolUse" ]; then
    # The switch is named HERE and not in "$warn": the deny below reuses that text, and
    # CC_REMIND does not silence a deny — naming it there would send the blocked reader
    # to a variable that changes nothing.
    msg="$warn CC_REMIND=off silences these."; return 0
  fi

  # ---- PreToolUse lane: deny the three blockable categories, at most TWICE per file ----
  #
  # WHY DENY AND NOT ASK: the model wrote the comment, so the model is the right
  # audience for the correction. `ask` would interrupt the HUMAN for a style nit,
  # once per tripping edit — during a task run that is dozens of prompts about
  # something the human did not write and cannot usefully adjudicate.
  #
  # WHY BOUNDED PER FILE: a deny the model cannot satisfy would otherwise loop.
  # The third attempt on the same file in the same session is allowed through,
  # and the PostToolUse lane warns on it instead — so a false positive costs at
  # most two extra turns, never a wedged session. Same bounding idea as
  # task-runner's one-block-per-commit completion gate. Two rather than one
  # because the bound is spent on the DENY, not on an observed write: when a
  # sibling hook denies the same call the write never lands, and a one-shot
  # bound was therefore consumed without the model ever seeing its own file.
  #
  # THE BOUND IS THE PRECONDITION, NOT A COURTESY. Every input the bound needs —
  # a session id, a cwd, a hashable path, and a marker that actually landed on disk —
  # is checked BEFORE the deny is emitted, and any one of them missing withholds the
  # deny entirely. An earlier revision wrote the marker with `2>/dev/null` and ignored
  # the result, which meant a read-only `.claude` state dir (sealed root when cwd was
  # absent, a 555 checkout, a container mount) produced a deny on every attempt with
  # nothing recording that it had fired: precisely the unwedgeable loop this comment
  # promised could not happen. Blocking is only defensible while it is bounded, so a
  # bound that cannot be recorded means no block at all.
  [ "$blockable" -gt 0 ] || return 1

  # Generated output declares itself in its own header; its banners are deliberate.
  printf '%s\n' "$added" | cd_generated && return 1

  # CONTEXT KEY, not session key. PostToolUse is the only hook channel that reaches
  # subagents at all, and a subagent shares its parent's session_id while getting its
  # own transcript. Keying a one-shot on session_id therefore dedups the worker against
  # nudges only the PARENT ever saw, so the context where most fan-out code is written
  # is the one context this never speaks in. Pattern and rationale: hooks/conventions.sh (context-key one-shot).
  sid=$(printf '%s' "$input" | jq -r '.transcript_path // .session_id // empty' 2>/dev/null)
  [ -n "$sid" ] || return 1                   # cannot bound the deny → do not block
  # `-d` as well as `-n`: a deleted project dir came back three levels deep holding only
  # the `mkdir -p` of this hook's state dir below. A cwd that is gone is also nowhere to
  # record the bound, so it withholds the deny on the same rule as the rest of this block.
  # Then the state ROOT, not the cwd. This comment said the payload cwd was "where the
  # session STARTED"; it is the shell's cwd and follows the model's `cd` (measured
  # 2026-09-25, rationale/2026-09-25-session-plugin-usage-review.md finding 2: app/Enums,
  # app/Models, then the repo root in one session). Under `<cwd>/.claude` every `cd` handed
  # each file a fresh DENY_CAP (scripts/__tests__/cwd-guard.test.sh replays it). The address `<root>/.claude/comment-discipline` is SHARED
  # with density.sh and verbosity.sh; all three moved to cc_state_root in one change
  # (0.23.0), because re-rooting one alone splits the bound. Does NOT catch a cwd that
  # exists but belongs to another checkout.
  [ -n "$cwd" ] && [ -d "$cwd" ] || return 1  # no cwd, or a cwd that is gone → nowhere to record the bound
  [ -n "$root" ] || return 1
  key=$(printf '%s' "$fp" | (command -v shasum >/dev/null 2>&1 && shasum || cksum) 2>/dev/null | cut -d' ' -f1)
  [ -n "$key" ] || return 1
  # THE KEY IS A PATH, SO IT MUST BE HASHED BEFORE IT CAN BE A FILENAME. `.transcript_path`
  # is an absolute path; interpolating it raw builds `…/blocked-/Users/…/x.jsonl-<key>`,
  # whose parents `mkdir -p "<root>/.claude/comment-discipline"` never creates. Every write
  # then fails, the withhold below fires, and the deny is silently absent on every edit of
  # every file — the tooth reads as present in this file and is gone in every real session.
  # Hashed with the same cksum idiom as hooks/conventions.sh (its `seen=` line), which got
  # this right.
  ctx=$(printf '%s' "$sid" | cksum 2>/dev/null | cut -d' ' -f1)
  [ -n "$ctx" ] || return 1
  dir=$(cc_plugin_state "$root" comment-discipline)
  marker="$dir/blocked-$ctx-$key"
  # BOUNDED RETRIES, not a one-shot. The bound is spent when this hook DENIES, but a
  # deny does not mean the write landed: any sibling PreToolUse hook denying the same
  # call (testing:protect-tests, secret-scanning/scan, command-guard, …) blocks it too,
  # and the old one-shot was already gone. The model then fixed the sibling's complaint,
  # re-wrote, and this hook was silent — the comment noise shipped. Measured 2026-09-15
  # with all 31 plugins installed; unreachable with this plugin alone, which is why it
  # survived. Two denies per file per session bounds a pathological loop exactly as the
  # one-shot did while surviving one co-firing deny.
  DENY_CAP=2
  # ATOMIC, because a counter file is not. `mkdir` either creates or fails, so two
  # parallel subagents editing one file cannot both read 0 and both write 1 — a
  # read-modify-write counter let the file be denied more than DENY_CAP times.
  # A legacy zero-byte marker from <=0.19.0 counts as one try, so an upgrade
  # mid-session does not hand a file a fresh budget.
  tries=0
  [ -e "$marker" ] && tries=1
  i=1
  while [ "$i" -le "$DENY_CAP" ]; do [ -d "$marker.d$i" ] && tries=$i; i=$((i + 1)); done
  [ "$tries" -ge "$DENY_CAP" ] && return 1
  mkdir -p "$dir" 2>/dev/null || return 1
  # The state dir ignores itself (0.18.3): a marker per denied file showed up as
  # untracked in every repo without a hand-written ignore line.
  [ -e "$dir/.gitignore" ] || printf '*\n' > "$dir/.gitignore" 2>/dev/null
  mkdir "$marker.d$((tries + 1))" 2>/dev/null || return 1 # lost the race → a sibling instance denied
  # RESIDUAL, stated rather than hidden: the bound is spent when this hook DENIES, and a
  # deny does not prove the write landed. Two co-firing siblings can still exhaust both
  # tries on writes that never happened, and the third edit then ships unchecked. Spending
  # the bound only on an observed write needs a PostToolUse handshake, which is a larger
  # change to a guard with 55 assertions; two tries survives the measured single-sibling
  # case, which is the one reproduced with all 31 plugins installed.
  reason=$(printf '%s Write the edit again without them: a comment restating the next line, a line of commented-out code, or a docblock tag that only repeats the signature has no fact to carry — delete it or move the fact to a name, a type, or a test. The default is no comment; a docblock earns a line only for what the signature cannot state. Blocked at most twice per file; after that an edit goes through with a warning instead. CC_COMMENT_GUARD=off disables this block for the session (CC_REMIND=off silences the warning it falls back to).' "$warn")
  msg=$reason; return 0
  }

  # jq builds the envelope so the message stays valid JSON whatever the comment text
  # contains. jq presence is guaranteed by the guard at the top of the block.
  emit() {
    if [ "$event" = "PreToolUse" ]; then
      jq -cn --arg r "$msg$1" \
        '{hookSpecificOutput:{hookEventName:"PreToolUse",permissionDecision:"deny",permissionDecisionReason:$r}}'
    else
      jq -cn --arg ctx "$msg$1" \
        '{hookSpecificOutput:{hookEventName:"PostToolUse",additionalContext:$ctx}}'
    fi
  }

  if [ "$tool" = Bash ]; then
    chunks=$(cc_bash_write_chunks "$cmd")
    [ -n "$chunks" ] || exit 0
    n=0; k=0
    while IFS= read -r l; do
      k=$((k + 1)); tgt=$(cc_bash_write_targets "${l#?}" | head -n 1)
      if [ -n "$tgt" ] && scan_governed "$tgt"; then n=$((n + 1)); ctgt[$n]=$tgt; chdr[$n]=${l#?}; cnum[$n]=$k; fi
    done <<EOF_C
$(printf '%s\n' "$chunks" | awk 'substr($0, 1, 1) == "\036"')
EOF_C
    [ "$n" -gt 0 ] || exit 0
    . "$(dirname "$0")/paths.sh" 2>/dev/null
    hascd=0; cd_has_cd "$cmd" && hascd=1
    c=1   # not `i`: scan_judge counts its deny markers with that name
    while [ "$c" -le "$n" ]; do
      if cd_chunk_mode "${chdr[$c]}" >/dev/null && cd_target_whole "${chdr[$c]}" "${ctgt[$c]}" \
         && fp=$(cd_bash_target "${ctgt[$c]}" "$cwd" "$hascd") \
         && scan_judge "$fp" "$(cd_chunk_text "$chunks" "${cnum[$c]}")"; then
        emit " Written by a Bash command: $(basename "$fp")."
        exit 0
      fi
      c=$((c + 1))
    done
  else
    fp=$(printf '%s' "$input" | jq -r '.tool_input.file_path // empty' 2>/dev/null) || exit 0
    added=$(printf '%s' "$input" | jq -r '
      [ .tool_input.content    // empty,
        .tool_input.new_string // empty,
        ( .tool_input.edits // [] | map(.new_string // empty) | join("\n") )
      ] | join("\n")' 2>/dev/null) || exit 0
    scan_judge "$fp" "$added" && emit ""
  fi
} 2>/dev/null
exit 0
