#!/usr/bin/env bash
# GENERATED by scripts/gen-codex — do not edit. Installs this marketplace's Codex subagents
# into your Codex agents dir. Codex plugins cannot bundle subagents, so this is out-of-band.
# Usage: bash codex/install-agents.sh [--force]   (CODEX_HOME defaults to ~/.codex)
set -euo pipefail
here="$(cd "$(dirname "$0")" && pwd)"
dest="${CODEX_HOME:-$HOME/.codex}/agents"
force="${1:-}"
mkdir -p "$dest"
placed=0
for f in "$here"/agents/*.toml; do
  [ -e "$f" ] || continue
  name="$(basename "$f")"
  target="$dest/$name"
  if [ -e "$target" ] && cmp -s "$f" "$target"; then
    continue                      # identical — idempotent no-op
  fi
  if [ -e "$target" ] && [ "$force" != "--force" ]; then
    echo "skip (exists and differs; pass --force to overwrite): $name" >&2
    continue
  fi
  cp "$f" "$target"
  echo "installed: $name"
  placed=$((placed + 1))
done
echo "$placed agent(s) placed in $dest"
